# Deployment parameters.
# The deployment process is divided into various stages.

# Deploy local L1.
deploy_l1: true

# Disable zkEVM contracts on L1 (not needed for standalone L1 Rollup).
deploy_zkevm_contracts_on_l1: false

# Disable zkEVM node and CDK peripheral databases.
deploy_databases: false

# Disable CDK central/trusted environment.
deploy_cdk_central_environment: false

# Disable CDK/bridge infrastructure.
deploy_cdk_bridge_infra: false

# Disable permissionless nodes (not required for standalone Rollup).
deploy_zkevm_permissionless_node: false

# Deploy Erigon node as sequencer for L1 Rollup.
deploy_cdk_erigon_node: true

# Disable observability stack (optional for standalone).
deploy_observability: false

# Disable Blockscout stack (optional).
deploy_l2_blockscout: false

# Disable ETH load balancer (not required for standalone).
deploy_blutgang: false

# Do not apply workloads during initial deployment.
apply_workload: false

args:
  # Suffix appended to service names.
  deployment_suffix: "-001"

  # Use Erigon as the sequencer.
  sequencer_type: "erigon"

  # Set data availability mode to rollup.
  data_availability_mode: rollup

  # Docker images and repositories used to spin up services.
  cdk_erigon_node_image: hermeznetwork/cdk-erigon:2.0.0-beta15
  toolbox_image: leovct/toolbox:0.0.1

  # Port configuration for L1 Rollup.
  l1_rpc_url: http://el-1-geth-lighthouse:8545
  l1_ws_url: ws://el-1-geth-lighthouse:8546
  l1_chain_id: 271828
  l1_preallocated_mnemonic: code code code code code code code code code code code quality
  l1_funding_amount: 100ether

  # Monitoring ports (optional; adjust if observability is enabled).
  prometheus_port: 9090
  grafana_port: 3000
  blockscout_public_port: 4000

  # Monitoring image versions (optional).
  prometheus_image: "prom/prometheus:v2.45.0"
  grafana_image: "grafana/grafana:10.0.3"

  # Workload configuration (disabled for initial deployment).
  workload_commands: []

  # Rollup configuration.
  zkevm_rollup_chain_id: 87654321
  zkevm_rollup_fork_id: 9
  erigon_strict_mode: true

  # Explorer URLs
  # prometheus
  l1_explorer_url: https://127.0.0.1:32789
  #l1_explorer_url: https://sepolia.etherscan.io/

  # Enable gas token contract
  zkevm_use_gas_token_contract: true

  # Gas token parameters.
  zkevm_gas_token_name: "OPEN"
  zkevm_gas_token_symbol: "BDK"
  zkevm_gas_token_decimals: 18
  zkevm_gas_token_supply: 84000000000000000000000000  # 84M tokens with 18 decimals

  # Gas Fee Configuration
  gas_fee_manager:
    enabled: true
    base_fee: "0.0001"  # Standard transaction base fee in OPEN BDK
    tiers:
      standard:
        multiplier: 1
        min_bandwidth: 33  # Guaranteed 1/3 of bandwidth
      fast:
        multiplier: 2
        max_bandwidth: 67  # Up to 2/3 remaining bandwidth
      priority:
        multiplier: 3
        max_bandwidth: 67  # Up to 2/3 total bandwidth
    dynamic_adjustment:
      enabled: true
      update_interval: 100  # blocks
      target_block_usage: 80  # percentage

  ## Tools versions
  polycli_version: v0.1.42
